### ISSUE TITLE
TypeError: PkgConfig is not a function

### ISSUE THREAD

**Issue by qiyingcong** [antfu/vite-plugin-package-config#6]
### Describe the bug

安装完 'vite-plugin-optimize-persist’  'vite-plugin-package-config'这两个插件，启动项目报错如下
PS C:\Users\97364\Desktop\ProjectCode\gzgd-admin> npm run dev

> vite-project@0.0.0 dev C:\Users\97364\Desktop\ProjectCode\gzgd-admin
> vite --host

{                                                                                                                                                     20:12:55
  default: [Getter]
} PkgConfig

 ERROR  failed to load config from C:\Users\97364\Desktop\ProjectCode\gzgd-admin\vite.config.ts                                                       20:12:55

 ERROR  error when starting dev server:                                                                                                               20:12:55
TypeError: PkgConfig is not a function
    at file:///C:/Users/97364/Desktop/ProjectCode/gzgd-admin/vite.config.ts.timestamp-1679487174009.mjs:46:5
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async loadConfigFromBundledFile (file:///C:/Users/97364/Desktop/ProjectCode/gzgd-admin/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62337:21)
    at async loadConfigFromFile (file:///C:/Users/97364/Desktop/ProjectCode/gzgd-admin/node_modules/vite/dist/node/chunks/dep-ca21228b.js:62222:28)
    at async resolveConfig (file:///C:/Users/97364/Desktop/ProjectCode/gzgd-admin/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61843:28)
    at async createServer (file:///C:/Users/97364/Desktop/ProjectCode/gzgd-admin/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61153:20)
    at async CAC.<anonymous> (file:///C:/Users/97364/Desktop/ProjectCode/gzgd-admin/node_modules/vite/dist/node/cli.js:734:24)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vite-project@0.0.0 dev: `vite --host`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vite-project@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\97364\AppData\Roaming\npm-cache\_logs\2023-03-22T12_12_55_518Z-debug.log
PS C:\Users\97364\Desktop\ProjectCode\gzgd-admin> 

### Reproduction

TypeError: PkgConfig is not a function

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
    Memory: 1.37 GB / 7.78 GB
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by luqiudi** [comment]
点头点头，俺也一样

**Comment by obito-t** [comment]
看看package.json是不是配置了"type": "module"，如果配置了的话，用下面的方式引入应该可以。

const require = createRequire(import.meta.url);
const {default: OptimizationPersist} = require('vite-plugin-optimize-persist');
const {default: PkgConfig} = require('vite-plugin-package-config');
